name: Docker Image Build

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        username: fahchen
        password: ${{ secrets.FAHCHEN_DOCKER_HUB_TOKEN }}

    - name: Get VERSION
      run: echo "::set-output name=VERSION::$(awk -F '=' '/ENV VERSION=/ { print $2 }' Dockerfile)"
      id: get-version

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          fahchen/elasticsearch-analysis-ik:${{ steps.get-version.outputs.VERSION }}
          fahchen/elasticsearch-analysis-ik:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
